version: '3'
services:

  api: 
    build: .
    image: webpage-builder
    container_name: webpage-builder
    restart: always
    command: ["daphne", "-b", "0.0.0.0", "-p", "9999", "config.asgi:application"]
    ports:
      - 9999:9999
